const mongoose = require("mongoose");
const Scrap = mongoose.model("Scrap", {
  name: { type: String, required: true, maxlength: 40 },
  condition: {
    type: String,
    required: true,
    enum: ["Comme neuf", "Très bon état", "Correct", "Abîmé", "Très abîmé"],
  },
  description: { type: String, minlength: 10, maxlength: 300, required: true },
  quantity: { type: Number, default: 1, required: true },
  price: { type: Number, required: true },
  isFree: { type: Boolean, required: true },
  isForSell: { type: Boolean, required: true },
  category: {
    type: [String],
    required: true,
    enum: [
      "Quincaillerie",
      "Outils",
      "Peinture",
      "Sol",
      "Electricité",
      "Plomberie",
      "Toiture",
      "Menuiserie",
      "Gros-oeuvre",
      "Jardin",
      "Divers",
    ],
  },
  pictures: { type: Array, required: false },
  homePickup: { type: Boolean, default: true },
  sending: { type: Boolean, default: false },
  weight: { type: String, required: true },
  material: { type: [String], required: true },
  height: { type: Number, required: false },
  //length
  length: { type: Number, required: false },
  mmLength: { type: Boolean, required: false },
  cmLength: { type: Boolean, required: false },
  mLength: { type: Boolean, required: false },
  //width
  width: { type: Number, required: false },
  mmWidth: { type: Boolean, required: false },
  cmWidth: { type: Boolean, required: false },
  mWidth: { type: Boolean, required: false },
  //thickness
  thickness: { type: Number, required: false },
  mmThickness: { type: Boolean, required: false },
  cmThickness: { type: Boolean, required: false },
  mThickness: { type: Boolean, required: false },
  //diameter
  diameter: { type: Number, required: false },
  mmDiameter: { type: Boolean, required: false },
  cmDiameter: { type: Boolean, required: false },
  mDiameter: { type: Boolean, required: false },
  //depth
  depth: { type: Number, required: false },
  mmDepth: { type: Boolean, required: false },
  cmDepth: { type: Boolean, required: false },
  mlDepth: { type: Boolean, required: false },
  //shape
  shape: {
    type: [String],
    required: false,
    enum: [
      "Rond",
      "Carré",
      "Rectangle",
      "Triangle",
      "Plat",
      "Ovoïde",
      "Pentagone",
      "Hexagone",
      "Octagone",
    ],
  },
  necessaryTool: { type: String, required: false },
  normAndLabel: { type: String, required: false },
  brand: { type: String, required: false },
  createdAt: { type: Date, default: Date.now },
  owner: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
  },
});
module.exports = Scrap;
