const mongoose = require("mongoose");
const Scrap = mongoose.model("Scrap", {
  name: { type: String, required: true },
  condition: { type: String, required: true },
  description: { type: String, minlength: 10, maxlength: 300, required: true },
  quantity: { type: Number, default: 1, required: true },
  price: { type: Number, min: 1, default: 1, required: true },
  category: {
    type: [String],
    required: true,
    enum: [
      "Quincaillerie",
      "Outils",
      "Peinture",
      "Sol",
      "Electricité",
      "Plomberie",
      "Toiture",
      "Menuiserie",
      "Gros-oeuvre",
      "Jardin",
      "Divers",
    ],
  },
  pictures: { type: Array, required: true },
  homePickup: { type: Boolean, default: true, required: true },
  weight: { type: Number, required: true },
  material: { type: [String], required: true },
  height: { type: Number, required: false },
  length: { type: Number, required: false },
  width: { type: Number, required: false },
  thickness: { type: Number, required: false },
  diameter: { type: Number, required: false },
  depth: { type: Number, required: false },
  shape: {
    type: [String],
    required: true,
    enum: [
      "rond",
      "carré",
      "rectangulaire",
      "triangulaire",
      "cruciform",
      "plat",
      "ovoïdal",
      "pentagonal",
      "hexagonal",
      "septagonal",
      "octogonal",
      "nonagonal",
      "decagonal",
      "autres",
    ],
  },
  necessaryTool: { type: String, required: false },
  normAndLabel: { type: String, required: false },
  brand: { type: String, required: false },
  createdAt: { type: Date, default: Date.now },
  owner: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
  },
});
module.exports = Scrap;
